### ISSUE TITLE
OfficeServ 7400

### ISSUE THREAD

**Issue by xpresslogistics2015** [brofield/pbxlog#1]
Hi there, interesting project! 
whenever I try to run this I get an error:
<code>
. HDR  INVALID panic: Error: "EOF": []
goroutine 1 [running]:
main.panicErr(0x9ea240, 0xc42001e060, 0x0, 0x0, 0x0)
	/opt/pbxlog/pbxlog.go:233 +0x141
main.main()
	/opt/pbxlog/pbxlog.go:199 +0x1e6
exit status 2
</code>

I am running this on debian.

My Go env:
<code>
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/administrator/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/administrator/work"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build327868719=/tmp/go-build -gno-record-gcc-switches"
</code>

Please help!

**Comment by brofield** [comment]
If you have configured it with a dump file and error file, it should dump
out the records that are causing the problem for it. It appears that you
are getting an EOF while reading though. I don't get that, so it might be
caused by a different PABX setup than I have. Do you have full access to
the PABX programming via osdm? If I can find the page that deals with the
SMDR records then we can compare settings.

Brodie
